insert into cities (city_id, city_name) values (1, 'Cockburn Town');
insert into cities (city_id, city_name) values (2, 'Bratislava');
insert into cities (city_id, city_name) values (3, 'Caigongzhuang');
insert into cities (city_id, city_name) values (4, 'Tojal');
insert into cities (city_id, city_name) values (5, 'Piskavica');
insert into cities (city_id, city_name) values (6, 'Puutuga');
insert into cities (city_id, city_name) values (7, 'Zouma');
insert into cities (city_id, city_name) values (8, 'General Levalle');
insert into cities (city_id, city_name) values (9, 'Shinjō');
insert into cities (city_id, city_name) values (10, 'Haikoudajie');
insert into cities (city_id, city_name) values (11, 'Xinchong');
insert into cities (city_id, city_name) values (12, 'Breda');
insert into cities (city_id, city_name) values (13, 'Yirshi');
insert into cities (city_id, city_name) values (14, 'Ganghwa-gun');
insert into cities (city_id, city_name) values (15, 'Baratan');
insert into cities (city_id, city_name) values (16, 'Sofo-Birnin-Gwari');
insert into cities (city_id, city_name) values (17, 'Balaka');
insert into cities (city_id, city_name) values (18, 'Stepnogorsk');
insert into cities (city_id, city_name) values (19, 'São Francisco do Sul');
insert into cities (city_id, city_name) values (20, 'Cañas');
insert into cities (city_id, city_name) values (21, 'Yelenendorf');
insert into cities (city_id, city_name) values (22, 'Linjiang');
insert into cities (city_id, city_name) values (23, 'Taihe');
insert into cities (city_id, city_name) values (24, 'Louis Trichardt');
insert into cities (city_id, city_name) values (25, 'Łazy');
insert into cities (city_id, city_name) values (26, 'Dimbokro');
insert into cities (city_id, city_name) values (27, 'Wafang');
insert into cities (city_id, city_name) values (28, 'Yambio');
insert into cities (city_id, city_name) values (29, 'Gavea');
insert into cities (city_id, city_name) values (30, 'Nanlü');
insert into cities (city_id, city_name) values (31, 'Spuž');
insert into cities (city_id, city_name) values (32, 'Shijing');
insert into cities (city_id, city_name) values (33, 'Mīrwāh Gorchani');
insert into cities (city_id, city_name) values (34, 'Yongshan');
insert into cities (city_id, city_name) values (35, 'Ponte');
insert into cities (city_id, city_name) values (36, 'Chodów');
insert into cities (city_id, city_name) values (37, 'Zarzis');
insert into cities (city_id, city_name) values (38, 'Soraya');
insert into cities (city_id, city_name) values (39, 'Zhouzai');
insert into cities (city_id, city_name) values (40, 'Croix');
insert into cities (city_id, city_name) values (41, 'Kapotnya');
insert into cities (city_id, city_name) values (42, 'Sila');
insert into cities (city_id, city_name) values (43, 'Kadupinang');
insert into cities (city_id, city_name) values (44, 'Sơn Trà');
insert into cities (city_id, city_name) values (45, 'João Alfredo');
insert into cities (city_id, city_name) values (46, 'Quetigny');
insert into cities (city_id, city_name) values (47, 'Vostryakovo');
insert into cities (city_id, city_name) values (48, 'Sel’tso');
insert into cities (city_id, city_name) values (49, 'Primorsko-Akhtarsk');
insert into cities (city_id, city_name) values (50, 'Kolwezi');
insert into cities (city_id, city_name) values (51, 'Zhongxiang');
insert into cities (city_id, city_name) values (52, 'Zhifudao');
insert into cities (city_id, city_name) values (53, 'Panyambungan');
insert into cities (city_id, city_name) values (54, 'Yanliang');
insert into cities (city_id, city_name) values (55, 'Charopó');
insert into cities (city_id, city_name) values (56, 'Tomar');
insert into cities (city_id, city_name) values (57, 'Rychvald');
insert into cities (city_id, city_name) values (58, 'Anfeng');
insert into cities (city_id, city_name) values (59, 'Huanggang');
insert into cities (city_id, city_name) values (60, 'Montecarlo');
insert into cities (city_id, city_name) values (61, 'Mirsíni');
insert into cities (city_id, city_name) values (62, 'Karlskrona');
insert into cities (city_id, city_name) values (63, 'Katumba');
insert into cities (city_id, city_name) values (64, 'Bugo');
insert into cities (city_id, city_name) values (65, 'Báguanos');
insert into cities (city_id, city_name) values (66, 'Aldeia da Bela Vista');
insert into cities (city_id, city_name) values (67, 'Pyt-Yakh');
insert into cities (city_id, city_name) values (68, 'Tost');
insert into cities (city_id, city_name) values (69, 'Leyuan');
insert into cities (city_id, city_name) values (70, 'Cockburn Town');
insert into cities (city_id, city_name) values (71, 'Ordino');
insert into cities (city_id, city_name) values (72, 'São Miguel do Rio Torto');
insert into cities (city_id, city_name) values (73, 'Stąporków');
insert into cities (city_id, city_name) values (74, 'Sámara');
insert into cities (city_id, city_name) values (75, 'New York City');
insert into cities (city_id, city_name) values (76, 'Chating');
insert into cities (city_id, city_name) values (77, 'Shiraoi');
insert into cities (city_id, city_name) values (78, 'Saint-Cloud');
insert into cities (city_id, city_name) values (79, 'Croix');
insert into cities (city_id, city_name) values (80, 'Lindesberg');
insert into cities (city_id, city_name) values (81, 'Nantes');
insert into cities (city_id, city_name) values (82, 'Kiev');
insert into cities (city_id, city_name) values (83, 'Harembo');
insert into cities (city_id, city_name) values (84, 'Plasy');
insert into cities (city_id, city_name) values (85, 'Västerhaninge');
insert into cities (city_id, city_name) values (86, 'Corail');
insert into cities (city_id, city_name) values (87, 'Ainaži');
insert into cities (city_id, city_name) values (88, 'Jinghai');
insert into cities (city_id, city_name) values (89, 'Floreşti');
insert into cities (city_id, city_name) values (90, 'Oganlima');
insert into cities (city_id, city_name) values (91, 'Shalqīya');
insert into cities (city_id, city_name) values (92, 'Saint-Brieuc');
insert into cities (city_id, city_name) values (93, 'Maras');
insert into cities (city_id, city_name) values (94, 'Hushan');
insert into cities (city_id, city_name) values (95, 'Curridabat');
insert into cities (city_id, city_name) values (96, 'Girsereng');
insert into cities (city_id, city_name) values (97, 'La Asunción');
insert into cities (city_id, city_name) values (98, 'Djohong');
insert into cities (city_id, city_name) values (99, 'Deder');
insert into cities (city_id, city_name) values (100, 'Snegiri');
insert into cities (city_id, city_name) values (101, 'Corujeira');
insert into cities (city_id, city_name) values (102, 'Ustyuzhna');
insert into cities (city_id, city_name) values (103, 'Péplos');
insert into cities (city_id, city_name) values (104, 'Beiwa');
insert into cities (city_id, city_name) values (105, 'Bašaid');
insert into cities (city_id, city_name) values (106, 'Jistebník');
insert into cities (city_id, city_name) values (107, 'Ketapang');
insert into cities (city_id, city_name) values (108, 'Kabasalan');
insert into cities (city_id, city_name) values (109, 'Kauditan');
insert into cities (city_id, city_name) values (110, 'Almaguer North');
insert into cities (city_id, city_name) values (111, 'Ozerki');
insert into cities (city_id, city_name) values (112, 'Zgornje Gorje');
insert into cities (city_id, city_name) values (113, 'Kota Kinabalu');
insert into cities (city_id, city_name) values (114, 'Pandasan');
insert into cities (city_id, city_name) values (115, 'Richmond');
insert into cities (city_id, city_name) values (116, 'Lusacan');
insert into cities (city_id, city_name) values (117, 'Nurota Shahri');
insert into cities (city_id, city_name) values (118, 'El Rincón');
insert into cities (city_id, city_name) values (119, 'Mayrtup');
insert into cities (city_id, city_name) values (120, 'Gaimán');
insert into cities (city_id, city_name) values (121, 'Itaporanga');
insert into cities (city_id, city_name) values (122, 'Mahébourg');
insert into cities (city_id, city_name) values (123, 'Jacksonville');
insert into cities (city_id, city_name) values (124, 'Kỳ Anh');
insert into cities (city_id, city_name) values (125, 'Jiling');
insert into cities (city_id, city_name) values (126, 'Lembung Tengah');
insert into cities (city_id, city_name) values (127, 'Yushikalasu');
insert into cities (city_id, city_name) values (128, 'Xizhong');
insert into cities (city_id, city_name) values (129, 'Telouet');
insert into cities (city_id, city_name) values (130, 'Arnelas');
insert into cities (city_id, city_name) values (131, 'Andorinha');
insert into cities (city_id, city_name) values (132, 'Zhengji');
insert into cities (city_id, city_name) values (133, 'Chelu');
insert into cities (city_id, city_name) values (134, 'Peskovka');
insert into cities (city_id, city_name) values (135, 'Uzgen');
insert into cities (city_id, city_name) values (136, 'Lulindi');
insert into cities (city_id, city_name) values (137, 'Zaqatala');
insert into cities (city_id, city_name) values (138, 'San Juan Sacatepéquez');
insert into cities (city_id, city_name) values (139, 'Colesberg');
insert into cities (city_id, city_name) values (140, 'Zhishan');
insert into cities (city_id, city_name) values (141, 'Rennes');
insert into cities (city_id, city_name) values (142, 'Göteborg');
insert into cities (city_id, city_name) values (143, 'L-Iklin');
insert into cities (city_id, city_name) values (144, 'Bahía Honda');
insert into cities (city_id, city_name) values (145, 'Komsomol’sk');
insert into cities (city_id, city_name) values (146, 'Xufeng');
insert into cities (city_id, city_name) values (147, 'Punsu');
insert into cities (city_id, city_name) values (148, 'Gislaved');
insert into cities (city_id, city_name) values (149, 'Moyamba');
insert into cities (city_id, city_name) values (150, 'Biyong');
insert into cities (city_id, city_name) values (151, 'Thị Trấn Thất Khê');
insert into cities (city_id, city_name) values (152, 'Cachón');
insert into cities (city_id, city_name) values (153, 'Kostel');
insert into cities (city_id, city_name) values (154, 'Roma');
insert into cities (city_id, city_name) values (155, 'Tiouli');
insert into cities (city_id, city_name) values (156, 'Narok');
insert into cities (city_id, city_name) values (157, 'Tadou');
insert into cities (city_id, city_name) values (158, 'Jingzhou');
insert into cities (city_id, city_name) values (159, 'Shuishaping');
insert into cities (city_id, city_name) values (160, 'Tupesy');
insert into cities (city_id, city_name) values (161, 'Keyi');
insert into cities (city_id, city_name) values (162, 'Nerchinsk');
insert into cities (city_id, city_name) values (163, 'Đắk Mâm');
insert into cities (city_id, city_name) values (164, 'Baisha');
insert into cities (city_id, city_name) values (165, 'Sangesi');
insert into cities (city_id, city_name) values (166, 'Manolo Fortich');
insert into cities (city_id, city_name) values (167, 'Haradzishcha');
insert into cities (city_id, city_name) values (168, 'Ras al-Khaimah');
insert into cities (city_id, city_name) values (169, 'Victoria');
insert into cities (city_id, city_name) values (170, 'Gualeguaychú');
insert into cities (city_id, city_name) values (171, 'Belize City');
insert into cities (city_id, city_name) values (172, 'Maebashi-shi');
insert into cities (city_id, city_name) values (173, 'Yên Lạc');
insert into cities (city_id, city_name) values (174, 'Colombes');
insert into cities (city_id, city_name) values (175, 'Ogden');
insert into cities (city_id, city_name) values (176, 'Nailong');
insert into cities (city_id, city_name) values (177, 'Gading');
insert into cities (city_id, city_name) values (178, 'Xinhuang');
insert into cities (city_id, city_name) values (179, 'Zhambyl');
insert into cities (city_id, city_name) values (180, 'Sukamaju');
insert into cities (city_id, city_name) values (181, 'København');
insert into cities (city_id, city_name) values (182, 'Bulasa');
insert into cities (city_id, city_name) values (183, 'Kamimaruko');
insert into cities (city_id, city_name) values (184, 'Iyo');
insert into cities (city_id, city_name) values (185, 'Tuopu');
insert into cities (city_id, city_name) values (186, 'Kholm');
insert into cities (city_id, city_name) values (187, 'Libenge');
insert into cities (city_id, city_name) values (188, 'Ebute Ikorodu');
insert into cities (city_id, city_name) values (189, 'Nancy');
insert into cities (city_id, city_name) values (190, 'Paraíso');
insert into cities (city_id, city_name) values (191, 'Chahe');
insert into cities (city_id, city_name) values (192, 'Isabela');
insert into cities (city_id, city_name) values (193, 'Priupskiy');
insert into cities (city_id, city_name) values (194, 'Banī Mazār');
insert into cities (city_id, city_name) values (195, 'Teknāf');
insert into cities (city_id, city_name) values (196, 'Rodionovo-Nesvetaiskoye');
insert into cities (city_id, city_name) values (197, 'Montreuil');
insert into cities (city_id, city_name) values (198, 'Longtang');
insert into cities (city_id, city_name) values (199, 'Erie');
insert into cities (city_id, city_name) values (200, 'Kiffa');
insert into cities (city_id, city_name) values (201, 'Wangying');
insert into cities (city_id, city_name) values (202, 'Bavorov');
insert into cities (city_id, city_name) values (203, 'Asan Kumbang');
insert into cities (city_id, city_name) values (204, 'Repki');
insert into cities (city_id, city_name) values (205, 'Toong');
insert into cities (city_id, city_name) values (206, 'Tengqiao');
insert into cities (city_id, city_name) values (207, 'Cheonan');
insert into cities (city_id, city_name) values (208, 'Batroûn');
insert into cities (city_id, city_name) values (209, 'Kensington');
insert into cities (city_id, city_name) values (210, 'Birmingham');
insert into cities (city_id, city_name) values (211, 'Sísion');
insert into cities (city_id, city_name) values (212, 'Marseille');
insert into cities (city_id, city_name) values (213, 'Vigo');
insert into cities (city_id, city_name) values (214, 'Alexandria');
insert into cities (city_id, city_name) values (215, 'Banqiaodian');
insert into cities (city_id, city_name) values (216, 'Zlín');
insert into cities (city_id, city_name) values (217, 'Huskvarna');
insert into cities (city_id, city_name) values (218, 'Tangjiawan');
insert into cities (city_id, city_name) values (219, 'La Maná');
insert into cities (city_id, city_name) values (220, 'Balta');
insert into cities (city_id, city_name) values (221, 'Xiniqi');
insert into cities (city_id, city_name) values (222, 'Salerno');
insert into cities (city_id, city_name) values (223, 'Xiache');
insert into cities (city_id, city_name) values (224, 'Kertabumi');
insert into cities (city_id, city_name) values (225, 'Aykhal');
insert into cities (city_id, city_name) values (226, 'Korem');
insert into cities (city_id, city_name) values (227, 'Lleida');
insert into cities (city_id, city_name) values (228, 'Fengyang');
insert into cities (city_id, city_name) values (229, 'Fentange');
insert into cities (city_id, city_name) values (230, 'Holice');
insert into cities (city_id, city_name) values (231, 'Ballisodare');
insert into cities (city_id, city_name) values (232, 'Xiapu');
insert into cities (city_id, city_name) values (233, 'Hougang');
insert into cities (city_id, city_name) values (234, 'Quixeramobim');
insert into cities (city_id, city_name) values (235, 'Ciénaga');
insert into cities (city_id, city_name) values (236, 'Nama');
insert into cities (city_id, city_name) values (237, 'Ol Kalou');
insert into cities (city_id, city_name) values (238, 'Dallas');
insert into cities (city_id, city_name) values (239, 'Plaju');
insert into cities (city_id, city_name) values (240, 'Santa Bárbara');
insert into cities (city_id, city_name) values (241, 'Maloarkhangel’sk');
insert into cities (city_id, city_name) values (242, 'Zvenigorod');
insert into cities (city_id, city_name) values (243, 'Shangzhang');
insert into cities (city_id, city_name) values (244, 'Estrada');
insert into cities (city_id, city_name) values (245, 'Lynchburg');
insert into cities (city_id, city_name) values (246, 'Dicamay');
insert into cities (city_id, city_name) values (247, 'Cocorná');
insert into cities (city_id, city_name) values (248, 'Berlin');
insert into cities (city_id, city_name) values (249, 'Mabayo');
insert into cities (city_id, city_name) values (250, 'Saba Yoi');
insert into cities (city_id, city_name) values (251, 'Jinping');
insert into cities (city_id, city_name) values (252, 'Medveditskiy');
insert into cities (city_id, city_name) values (253, 'Sukolilo');
insert into cities (city_id, city_name) values (254, '5 de Mayo');
insert into cities (city_id, city_name) values (255, 'Rebrikha');
insert into cities (city_id, city_name) values (256, 'Sihanoukville');
insert into cities (city_id, city_name) values (257, 'Longhua');
insert into cities (city_id, city_name) values (258, 'Dushu');
insert into cities (city_id, city_name) values (259, 'Aoqiao');
insert into cities (city_id, city_name) values (260, 'Tefé');
insert into cities (city_id, city_name) values (261, 'Mistřice');
insert into cities (city_id, city_name) values (262, 'Shangjiangxu');
insert into cities (city_id, city_name) values (263, 'Calvário');
insert into cities (city_id, city_name) values (264, 'Ribeira do Pombal');
insert into cities (city_id, city_name) values (265, 'Coasa');
insert into cities (city_id, city_name) values (266, 'Guinoaliuan');
insert into cities (city_id, city_name) values (267, 'Karlsruhe');
insert into cities (city_id, city_name) values (268, 'Nandong');
insert into cities (city_id, city_name) values (269, 'Secunda');
insert into cities (city_id, city_name) values (270, 'Kebonkai');
insert into cities (city_id, city_name) values (271, 'Geneng');
insert into cities (city_id, city_name) values (272, 'Ipoh');
insert into cities (city_id, city_name) values (273, 'Taubaté');
insert into cities (city_id, city_name) values (274, 'Roscoff');
insert into cities (city_id, city_name) values (275, 'Trinity Ville');
insert into cities (city_id, city_name) values (276, 'Taishang');
insert into cities (city_id, city_name) values (277, 'Dietaisi');
insert into cities (city_id, city_name) values (278, 'Vila Nova de Gaia');
insert into cities (city_id, city_name) values (279, 'Itanhandu');
insert into cities (city_id, city_name) values (280, 'Vyborg');
insert into cities (city_id, city_name) values (281, 'Lleida');
insert into cities (city_id, city_name) values (282, 'Peddie');
insert into cities (city_id, city_name) values (283, 'Changyŏn');
insert into cities (city_id, city_name) values (284, 'Cataguases');
insert into cities (city_id, city_name) values (285, 'Pajaten');
insert into cities (city_id, city_name) values (286, 'Sosnovoborsk');
insert into cities (city_id, city_name) values (287, 'Czerwionka-Leszczyny');
insert into cities (city_id, city_name) values (288, 'Trzebieszów');
insert into cities (city_id, city_name) values (289, 'Huancapallac');
insert into cities (city_id, city_name) values (290, 'Borda da Mata');
insert into cities (city_id, city_name) values (291, 'Dongping');
insert into cities (city_id, city_name) values (292, 'Pangkalanbunut');
insert into cities (city_id, city_name) values (293, 'Tchintabaraden');
insert into cities (city_id, city_name) values (294, 'Central');
insert into cities (city_id, city_name) values (295, 'Huilong');
insert into cities (city_id, city_name) values (296, 'Xunhe');
insert into cities (city_id, city_name) values (297, 'Bellavista');
insert into cities (city_id, city_name) values (298, 'Frederiksberg');
insert into cities (city_id, city_name) values (299, 'Wuchagou');
insert into cities (city_id, city_name) values (300, 'Nungwi');
insert into cities (city_id, city_name) values (301, 'Kowalewo Pomorskie');
insert into cities (city_id, city_name) values (302, 'Cavadas');
insert into cities (city_id, city_name) values (303, 'San Juan del Cesar');
insert into cities (city_id, city_name) values (304, 'Puerto Tejada');
insert into cities (city_id, city_name) values (305, 'Bara Datu');
insert into cities (city_id, city_name) values (306, 'Gaoling');
insert into cities (city_id, city_name) values (307, 'Mor Laok');
insert into cities (city_id, city_name) values (308, 'Zouparria do Monte');
insert into cities (city_id, city_name) values (309, 'Zhongxin');
insert into cities (city_id, city_name) values (310, 'Bulbul');
insert into cities (city_id, city_name) values (311, 'Lokorae');
insert into cities (city_id, city_name) values (312, 'Oxelösund');
insert into cities (city_id, city_name) values (313, 'Zarechnyy');
insert into cities (city_id, city_name) values (314, 'Liuduzhai');
insert into cities (city_id, city_name) values (315, 'Mae Wang');
insert into cities (city_id, city_name) values (316, 'Quipot');
insert into cities (city_id, city_name) values (317, 'Sandakan');
insert into cities (city_id, city_name) values (318, 'La Curva');
insert into cities (city_id, city_name) values (319, 'Chor');
insert into cities (city_id, city_name) values (320, 'Vynohradiv');
insert into cities (city_id, city_name) values (321, 'Corbeil-Essonnes');
insert into cities (city_id, city_name) values (322, 'Takanabe');
insert into cities (city_id, city_name) values (323, 'Gudang');
insert into cities (city_id, city_name) values (324, 'Kajansi');
insert into cities (city_id, city_name) values (325, 'Orlando');
insert into cities (city_id, city_name) values (326, 'Sekarjalak');
insert into cities (city_id, city_name) values (327, 'Vrbice');
insert into cities (city_id, city_name) values (328, 'Manay');
insert into cities (city_id, city_name) values (329, 'Cabugao');
insert into cities (city_id, city_name) values (330, 'Przecław');
insert into cities (city_id, city_name) values (331, 'Sokal’');
insert into cities (city_id, city_name) values (332, 'Zbýšov');
insert into cities (city_id, city_name) values (333, 'Ituiutaba');
insert into cities (city_id, city_name) values (334, 'Palaiópyrgos');
insert into cities (city_id, city_name) values (335, 'Żarki');
insert into cities (city_id, city_name) values (336, 'Klokot');
insert into cities (city_id, city_name) values (337, 'Koh Tao');
insert into cities (city_id, city_name) values (338, 'Hexi');
insert into cities (city_id, city_name) values (339, 'Young');
insert into cities (city_id, city_name) values (340, 'Barong');
insert into cities (city_id, city_name) values (341, 'Mazkeret Batya');
insert into cities (city_id, city_name) values (342, 'Druzhny');
insert into cities (city_id, city_name) values (343, 'Jibiya');
insert into cities (city_id, city_name) values (344, 'Uglyanets');
insert into cities (city_id, city_name) values (345, 'Cacoal');
insert into cities (city_id, city_name) values (346, 'Jamao al Norte');
insert into cities (city_id, city_name) values (347, 'Qingxi');
insert into cities (city_id, city_name) values (348, 'Esperanza');
insert into cities (city_id, city_name) values (349, 'Vatutino');
insert into cities (city_id, city_name) values (350, 'Tonga');
insert into cities (city_id, city_name) values (351, 'Garoua Boulaï');
insert into cities (city_id, city_name) values (352, 'Āshtīān');
insert into cities (city_id, city_name) values (353, 'La Paz Centro');
insert into cities (city_id, city_name) values (354, 'Sampaloc');
insert into cities (city_id, city_name) values (355, 'Hongwei');
insert into cities (city_id, city_name) values (356, 'West End');
insert into cities (city_id, city_name) values (357, 'P’asanauri');
insert into cities (city_id, city_name) values (358, 'Keyinhe');
insert into cities (city_id, city_name) values (359, 'Baras');
insert into cities (city_id, city_name) values (360, 'Firá');
insert into cities (city_id, city_name) values (361, 'Lubumbashi');
insert into cities (city_id, city_name) values (362, 'Sidomulyo Kulon');
insert into cities (city_id, city_name) values (363, 'San Mateo');
insert into cities (city_id, city_name) values (364, 'Girón');
insert into cities (city_id, city_name) values (365, 'Dongxi');
insert into cities (city_id, city_name) values (366, 'Jiangshan');
insert into cities (city_id, city_name) values (367, 'Cemara');
insert into cities (city_id, city_name) values (368, 'Sujitan');
insert into cities (city_id, city_name) values (369, 'Shakhta');
insert into cities (city_id, city_name) values (370, 'Chortkiv');
insert into cities (city_id, city_name) values (371, 'Lākshām');
insert into cities (city_id, city_name) values (372, 'Pulo');
insert into cities (city_id, city_name) values (373, 'Collingwood');
insert into cities (city_id, city_name) values (374, 'Asíni');
insert into cities (city_id, city_name) values (375, 'Johanneshov');
insert into cities (city_id, city_name) values (376, 'Unden');
insert into cities (city_id, city_name) values (377, 'Matsushima');
insert into cities (city_id, city_name) values (378, 'Verdun');
insert into cities (city_id, city_name) values (379, 'Nong Yasai');
insert into cities (city_id, city_name) values (380, 'Milot');
insert into cities (city_id, city_name) values (381, 'Kotovs’k');
insert into cities (city_id, city_name) values (382, 'Toulouse');
insert into cities (city_id, city_name) values (383, 'Zamość');
insert into cities (city_id, city_name) values (384, 'Mbaïki');
insert into cities (city_id, city_name) values (385, 'Maevatanana');
insert into cities (city_id, city_name) values (386, 'Heimahe');
insert into cities (city_id, city_name) values (387, 'Diré');
insert into cities (city_id, city_name) values (388, 'Ciparasi');
insert into cities (city_id, city_name) values (389, 'Sing Buri');
insert into cities (city_id, city_name) values (390, 'Karangsono');
insert into cities (city_id, city_name) values (391, 'Nadezhda');
insert into cities (city_id, city_name) values (392, 'Kalýves Polygýrou');
insert into cities (city_id, city_name) values (393, 'Dalgān');
insert into cities (city_id, city_name) values (394, 'Senekal');
insert into cities (city_id, city_name) values (395, 'Paris 01');
insert into cities (city_id, city_name) values (396, 'Zhaxirabdain');
insert into cities (city_id, city_name) values (397, 'Baoquan');
insert into cities (city_id, city_name) values (398, 'Dumbéa');
insert into cities (city_id, city_name) values (399, 'Outokumpu');
insert into cities (city_id, city_name) values (400, 'Guoduwan');
insert into cities (city_id, city_name) values (401, 'Fontenay-sous-Bois');
insert into cities (city_id, city_name) values (402, 'Mulleriyawa');
insert into cities (city_id, city_name) values (403, 'Begang');
insert into cities (city_id, city_name) values (404, 'Ongandjera');
insert into cities (city_id, city_name) values (405, 'Sumoto');
insert into cities (city_id, city_name) values (406, 'Laborie');
insert into cities (city_id, city_name) values (407, 'Lensk');
insert into cities (city_id, city_name) values (408, 'Megalochórion');
insert into cities (city_id, city_name) values (409, 'Shisandaogou');
insert into cities (city_id, city_name) values (410, 'Huishi');
insert into cities (city_id, city_name) values (411, 'Chino');
insert into cities (city_id, city_name) values (412, 'Velká Polom');
insert into cities (city_id, city_name) values (413, 'Göteborg');
insert into cities (city_id, city_name) values (414, 'Qujing');
insert into cities (city_id, city_name) values (415, 'Maru');
insert into cities (city_id, city_name) values (416, 'Fulu');
insert into cities (city_id, city_name) values (417, 'Ketapang');
insert into cities (city_id, city_name) values (418, 'Tudela');
insert into cities (city_id, city_name) values (419, 'Sigay');
insert into cities (city_id, city_name) values (420, 'Potou');
insert into cities (city_id, city_name) values (421, 'Bendosari');
insert into cities (city_id, city_name) values (422, 'Abangay');
insert into cities (city_id, city_name) values (423, 'Xinshi');
insert into cities (city_id, city_name) values (424, 'Heshui');
insert into cities (city_id, city_name) values (425, 'Gio Linh');
insert into cities (city_id, city_name) values (426, 'Xingfu');
insert into cities (city_id, city_name) values (427, 'Pinaring');
insert into cities (city_id, city_name) values (428, 'Valada');
insert into cities (city_id, city_name) values (429, 'Almafuerte');
insert into cities (city_id, city_name) values (430, 'Palhoça');
insert into cities (city_id, city_name) values (431, 'Aix-en-Provence');
insert into cities (city_id, city_name) values (432, 'Kivijärvi');
insert into cities (city_id, city_name) values (433, 'Carrigtwohill');
insert into cities (city_id, city_name) values (434, 'Padangtiji');
insert into cities (city_id, city_name) values (435, 'Besah');
insert into cities (city_id, city_name) values (436, 'Montego Bay');
insert into cities (city_id, city_name) values (437, 'Araranguá');
insert into cities (city_id, city_name) values (438, 'Saint-Bruno-de-Montarville');
insert into cities (city_id, city_name) values (439, 'Woloara');
insert into cities (city_id, city_name) values (440, 'Tian’an');
insert into cities (city_id, city_name) values (441, 'Malaya Purga');
insert into cities (city_id, city_name) values (442, 'Ţūlkarm');
insert into cities (city_id, city_name) values (443, 'Yangshan');
insert into cities (city_id, city_name) values (444, 'Pandan');
insert into cities (city_id, city_name) values (445, 'Oshawa');
insert into cities (city_id, city_name) values (446, 'Shuihu');
insert into cities (city_id, city_name) values (447, 'Songshan');
insert into cities (city_id, city_name) values (448, 'Ramat Yishay');
insert into cities (city_id, city_name) values (449, 'Funan Chengguanzhen');
insert into cities (city_id, city_name) values (450, 'Granada');
insert into cities (city_id, city_name) values (451, 'Cataguases');
insert into cities (city_id, city_name) values (452, 'Pataha');
insert into cities (city_id, city_name) values (453, 'Cantapoy');
insert into cities (city_id, city_name) values (454, 'Kiritsy');
insert into cities (city_id, city_name) values (455, 'Sangatta');
insert into cities (city_id, city_name) values (456, 'Paradela');
insert into cities (city_id, city_name) values (457, 'Laju Kidul');
insert into cities (city_id, city_name) values (458, 'Waru');
insert into cities (city_id, city_name) values (459, 'Banocboc');
insert into cities (city_id, city_name) values (460, 'Obo');
insert into cities (city_id, city_name) values (461, 'Donghui');
insert into cities (city_id, city_name) values (462, 'Неготино');
insert into cities (city_id, city_name) values (463, 'Santa Monica');
insert into cities (city_id, city_name) values (464, 'Chengdong');
insert into cities (city_id, city_name) values (465, 'Phú Thái');
insert into cities (city_id, city_name) values (466, 'Massaranduba');
insert into cities (city_id, city_name) values (467, 'Krajan Dua Putukrejo');
insert into cities (city_id, city_name) values (468, 'Stockholm');
insert into cities (city_id, city_name) values (469, 'Ad Dujayl');
insert into cities (city_id, city_name) values (470, 'Santiago');
insert into cities (city_id, city_name) values (471, 'Sumberdadi');
insert into cities (city_id, city_name) values (472, 'Querecotillo');
insert into cities (city_id, city_name) values (473, 'Miatli');
insert into cities (city_id, city_name) values (474, 'Bumbuna');
insert into cities (city_id, city_name) values (475, 'Sinŭiju');
insert into cities (city_id, city_name) values (476, 'Kolomyya');
insert into cities (city_id, city_name) values (477, 'Jiantian');
insert into cities (city_id, city_name) values (478, 'Dístomo');
insert into cities (city_id, city_name) values (479, 'Gorna Oryakhovitsa');
insert into cities (city_id, city_name) values (480, 'Mahekou');
insert into cities (city_id, city_name) values (481, 'Kedungtulup');
insert into cities (city_id, city_name) values (482, 'Uścimów Stary');
insert into cities (city_id, city_name) values (483, 'Asheville');
insert into cities (city_id, city_name) values (484, 'Kousa');
insert into cities (city_id, city_name) values (485, 'Belize City');
insert into cities (city_id, city_name) values (486, 'Firá');
insert into cities (city_id, city_name) values (487, 'Tyczyn');
insert into cities (city_id, city_name) values (488, 'Al Wuday‘');
insert into cities (city_id, city_name) values (489, 'Labrang');
insert into cities (city_id, city_name) values (490, 'Sumberdangdang');
insert into cities (city_id, city_name) values (491, 'Leran Kulon');
insert into cities (city_id, city_name) values (492, 'Auch');
insert into cities (city_id, city_name) values (493, 'Kokopo');
insert into cities (city_id, city_name) values (494, 'Khasht’arrak');
insert into cities (city_id, city_name) values (495, 'Gandiaye');
insert into cities (city_id, city_name) values (496, 'Jandayan');
insert into cities (city_id, city_name) values (497, 'Growong Lor');
insert into cities (city_id, city_name) values (498, 'Siwalan');
insert into cities (city_id, city_name) values (499, 'Sélestat');
insert into cities (city_id, city_name) values (500, 'Anseong');
insert into cities (city_id, city_name) values (501, 'Doroslovo');
insert into cities (city_id, city_name) values (502, 'Santana de Parnaíba');
insert into cities (city_id, city_name) values (503, 'Kuala Lumpur');
insert into cities (city_id, city_name) values (504, 'Jangkungkusumo');
insert into cities (city_id, city_name) values (505, 'Nagrog');
insert into cities (city_id, city_name) values (506, 'Franco da Rocha');
insert into cities (city_id, city_name) values (507, 'Jorochito');
insert into cities (city_id, city_name) values (508, 'Pápa');
insert into cities (city_id, city_name) values (509, 'Infonavit');
insert into cities (city_id, city_name) values (510, 'Wāling');
insert into cities (city_id, city_name) values (511, 'Ipoh');
insert into cities (city_id, city_name) values (512, 'Hagi');
insert into cities (city_id, city_name) values (513, 'Rancabolang');
insert into cities (city_id, city_name) values (514, 'Siso');
insert into cities (city_id, city_name) values (515, 'Mandesan');
insert into cities (city_id, city_name) values (516, 'Gulong');
insert into cities (city_id, city_name) values (517, 'Orléans');
insert into cities (city_id, city_name) values (518, 'Mont-Saint-Aignan');
insert into cities (city_id, city_name) values (519, 'Fezna');
insert into cities (city_id, city_name) values (520, 'Simpangpasir');
insert into cities (city_id, city_name) values (521, 'Loma Bonita');
insert into cities (city_id, city_name) values (522, 'Namboongan');
insert into cities (city_id, city_name) values (523, 'Songhu');
insert into cities (city_id, city_name) values (524, 'Volodarsk');
insert into cities (city_id, city_name) values (525, 'Uusikaupunki');
insert into cities (city_id, city_name) values (526, 'Kairouan');
insert into cities (city_id, city_name) values (527, 'Třinec');
insert into cities (city_id, city_name) values (528, 'Sudimanik');
insert into cities (city_id, city_name) values (529, 'Zhirnovsk');
insert into cities (city_id, city_name) values (530, 'Batangtoru');
insert into cities (city_id, city_name) values (531, 'Jihuluntu Sumu');
insert into cities (city_id, city_name) values (532, 'Strängnäs');
insert into cities (city_id, city_name) values (533, 'Baytā al Fawqā');
insert into cities (city_id, city_name) values (534, 'Nakhon Ratchasima');
insert into cities (city_id, city_name) values (535, 'Horodok');
insert into cities (city_id, city_name) values (536, 'Cikeusal');
insert into cities (city_id, city_name) values (537, 'Inđija');
insert into cities (city_id, city_name) values (538, 'L''Union');
insert into cities (city_id, city_name) values (539, 'Tianfen');
insert into cities (city_id, city_name) values (540, 'Ujung');
insert into cities (city_id, city_name) values (541, 'Bhamo');
insert into cities (city_id, city_name) values (542, 'Lukolela');
insert into cities (city_id, city_name) values (543, 'Shangshuai');
insert into cities (city_id, city_name) values (544, 'Shiqian');
insert into cities (city_id, city_name) values (545, 'Napanee Downtown');
insert into cities (city_id, city_name) values (546, 'Canelas');
insert into cities (city_id, city_name) values (547, 'Tai Po');
insert into cities (city_id, city_name) values (548, 'Zamora');
insert into cities (city_id, city_name) values (549, 'Viñales');
insert into cities (city_id, city_name) values (550, 'Quimilí');
insert into cities (city_id, city_name) values (551, 'Delodpeken');
insert into cities (city_id, city_name) values (552, 'Svecha');
insert into cities (city_id, city_name) values (553, 'Bertelhe');
insert into cities (city_id, city_name) values (554, 'Nanao');
insert into cities (city_id, city_name) values (555, 'Nowosielce-Gniewosz');
insert into cities (city_id, city_name) values (556, 'Wan’an');
insert into cities (city_id, city_name) values (557, 'Chervonopartyzans’k');
insert into cities (city_id, city_name) values (558, 'Xiaolan');
insert into cities (city_id, city_name) values (559, 'Krong Pi Nang');
insert into cities (city_id, city_name) values (560, 'Carumas');
insert into cities (city_id, city_name) values (561, 'Dalazi');
insert into cities (city_id, city_name) values (562, 'Sukamaju');
insert into cities (city_id, city_name) values (563, 'Jutaí');
insert into cities (city_id, city_name) values (564, 'Manggekompo');
insert into cities (city_id, city_name) values (565, 'San Francisco');
insert into cities (city_id, city_name) values (566, 'Proástion');
insert into cities (city_id, city_name) values (567, 'Borgarnes');
insert into cities (city_id, city_name) values (568, 'Shiyun');
insert into cities (city_id, city_name) values (569, 'Minuwangoda');
insert into cities (city_id, city_name) values (570, 'Maliq');
insert into cities (city_id, city_name) values (571, 'Baixi');
insert into cities (city_id, city_name) values (572, 'Padre Nabeto');
insert into cities (city_id, city_name) values (573, 'Changshan');
insert into cities (city_id, city_name) values (574, 'Montpellier');
insert into cities (city_id, city_name) values (575, 'Umeå');
insert into cities (city_id, city_name) values (576, 'Matou');
insert into cities (city_id, city_name) values (577, 'Wadi');
insert into cities (city_id, city_name) values (578, 'Lauro de Freitas');
insert into cities (city_id, city_name) values (579, 'Laboulaye');
insert into cities (city_id, city_name) values (580, 'Hīsh');
insert into cities (city_id, city_name) values (581, 'Keffin Hausa');
insert into cities (city_id, city_name) values (582, 'Datan');
insert into cities (city_id, city_name) values (583, 'Greensboro');
insert into cities (city_id, city_name) values (584, 'Netvořice');
insert into cities (city_id, city_name) values (585, 'Vedène');
insert into cities (city_id, city_name) values (586, 'Pasco');
insert into cities (city_id, city_name) values (587, 'Brušperk');
insert into cities (city_id, city_name) values (588, 'Åkersberga');
insert into cities (city_id, city_name) values (589, 'Jatirejo');
insert into cities (city_id, city_name) values (590, 'Carrascal');
insert into cities (city_id, city_name) values (591, 'Orléans');
insert into cities (city_id, city_name) values (592, 'Ihuari');
insert into cities (city_id, city_name) values (593, 'Magole');
insert into cities (city_id, city_name) values (594, 'Užice');
insert into cities (city_id, city_name) values (595, 'Xugu');
insert into cities (city_id, city_name) values (596, 'Bayantal');
insert into cities (city_id, city_name) values (597, 'Ādam');
insert into cities (city_id, city_name) values (598, 'Neglasari');
insert into cities (city_id, city_name) values (599, 'Krajan Karangsari');
insert into cities (city_id, city_name) values (600, 'Banyutengah');
insert into cities (city_id, city_name) values (601, 'Pertunmaa');
insert into cities (city_id, city_name) values (602, 'Orahovac');
insert into cities (city_id, city_name) values (603, 'Taiyuan');
insert into cities (city_id, city_name) values (604, 'Karangparwa');
insert into cities (city_id, city_name) values (605, 'Kriel');
insert into cities (city_id, city_name) values (606, 'Pechenga');
insert into cities (city_id, city_name) values (607, 'Ibarra');
insert into cities (city_id, city_name) values (608, 'Ijuí');
insert into cities (city_id, city_name) values (609, 'Sarmīn');
insert into cities (city_id, city_name) values (610, 'Zhoupi');
insert into cities (city_id, city_name) values (611, 'Nandasmo');
insert into cities (city_id, city_name) values (612, 'Dongshan');
insert into cities (city_id, city_name) values (613, 'Wengyang');
insert into cities (city_id, city_name) values (614, 'Quţūr');
insert into cities (city_id, city_name) values (615, 'Chaem Luang');
insert into cities (city_id, city_name) values (616, 'Jilma');
insert into cities (city_id, city_name) values (617, 'Raminho');
insert into cities (city_id, city_name) values (618, 'Al Balyanā');
insert into cities (city_id, city_name) values (619, 'Villavicencio');
insert into cities (city_id, city_name) values (620, 'Bhokadoke');
insert into cities (city_id, city_name) values (621, 'Sintra');
insert into cities (city_id, city_name) values (622, 'Ngozi');
insert into cities (city_id, city_name) values (623, 'Jiaohu');
insert into cities (city_id, city_name) values (624, 'Xiping');
insert into cities (city_id, city_name) values (625, 'Sabang');
insert into cities (city_id, city_name) values (626, 'Payxambabazar');
insert into cities (city_id, city_name) values (627, 'Hofors');
insert into cities (city_id, city_name) values (628, 'Xi’an');
insert into cities (city_id, city_name) values (629, 'Jimaguayú');
insert into cities (city_id, city_name) values (630, 'Sopo');
insert into cities (city_id, city_name) values (631, 'Ursk');
insert into cities (city_id, city_name) values (632, 'Sanlanbahai');
insert into cities (city_id, city_name) values (633, 'Shicheng');
insert into cities (city_id, city_name) values (634, 'Undurkhaan');
insert into cities (city_id, city_name) values (635, 'Longtang');
insert into cities (city_id, city_name) values (636, 'Köln');
insert into cities (city_id, city_name) values (637, 'Kaleybar');
insert into cities (city_id, city_name) values (638, 'Pyay');
insert into cities (city_id, city_name) values (639, 'Na Muen');
insert into cities (city_id, city_name) values (640, 'Sentul');
insert into cities (city_id, city_name) values (641, 'Marcovia');
insert into cities (city_id, city_name) values (642, 'Shikou');
insert into cities (city_id, city_name) values (643, 'Thị Trấn Hùng Quốc');
insert into cities (city_id, city_name) values (644, 'Bima');
insert into cities (city_id, city_name) values (645, 'Orange');
insert into cities (city_id, city_name) values (646, 'Grande Rivière du Nord');
insert into cities (city_id, city_name) values (647, 'Firenze');
insert into cities (city_id, city_name) values (648, 'Karangsari');
insert into cities (city_id, city_name) values (649, 'Turkestan');
insert into cities (city_id, city_name) values (650, 'Tlogowungu');
insert into cities (city_id, city_name) values (651, 'Andongsari');
insert into cities (city_id, city_name) values (652, 'Yanac');
insert into cities (city_id, city_name) values (653, 'Willemstad');
insert into cities (city_id, city_name) values (654, 'Itoman');
insert into cities (city_id, city_name) values (655, 'Chongkan');
insert into cities (city_id, city_name) values (656, 'Gangmian');
insert into cities (city_id, city_name) values (657, 'Troitskiy');
insert into cities (city_id, city_name) values (658, 'Fatuulan');
insert into cities (city_id, city_name) values (659, 'Perosinho');
insert into cities (city_id, city_name) values (660, 'Avallon');
insert into cities (city_id, city_name) values (661, 'Blumbang');
insert into cities (city_id, city_name) values (662, 'Reszel');
insert into cities (city_id, city_name) values (663, 'Peraía');
insert into cities (city_id, city_name) values (664, 'Mamboma');
insert into cities (city_id, city_name) values (665, 'Nangang');
insert into cities (city_id, city_name) values (666, 'San Agustín de Valle Fértil');
insert into cities (city_id, city_name) values (667, 'Limoges');
insert into cities (city_id, city_name) values (668, 'Bichura');
insert into cities (city_id, city_name) values (669, 'Dongshan');
insert into cities (city_id, city_name) values (670, 'Živinice');
insert into cities (city_id, city_name) values (671, 'Otaslavice');
insert into cities (city_id, city_name) values (672, 'Knyaginino');
insert into cities (city_id, city_name) values (673, 'Shi’an');
insert into cities (city_id, city_name) values (674, 'Tvarožná');
insert into cities (city_id, city_name) values (675, 'Węgierska Górka');
insert into cities (city_id, city_name) values (676, 'Junín');
insert into cities (city_id, city_name) values (677, 'Lišov');
insert into cities (city_id, city_name) values (678, 'Popielów');
insert into cities (city_id, city_name) values (679, 'Carhuamayo');
insert into cities (city_id, city_name) values (680, 'Fëdorovskoye');
insert into cities (city_id, city_name) values (681, 'Marādah');
insert into cities (city_id, city_name) values (682, 'Czarnocin');
insert into cities (city_id, city_name) values (683, 'Karangsari');
insert into cities (city_id, city_name) values (684, 'Benoni');
insert into cities (city_id, city_name) values (685, 'Caicó');
insert into cities (city_id, city_name) values (686, 'Hernando');
insert into cities (city_id, city_name) values (687, 'Xinghe Chengguanzhen');
insert into cities (city_id, city_name) values (688, 'Kamensk-Shakhtinskiy');
insert into cities (city_id, city_name) values (689, 'Somovo');
insert into cities (city_id, city_name) values (690, 'Chynadiyovo');
insert into cities (city_id, city_name) values (691, 'Chust Shahri');
insert into cities (city_id, city_name) values (692, 'Tavira');
insert into cities (city_id, city_name) values (693, 'Sepanjang');
insert into cities (city_id, city_name) values (694, 'Monastir');
insert into cities (city_id, city_name) values (695, 'Shuiche');
insert into cities (city_id, city_name) values (696, 'Mandaluyong City');
insert into cities (city_id, city_name) values (697, 'Salt Lake City');
insert into cities (city_id, city_name) values (698, 'Ramalhal');
insert into cities (city_id, city_name) values (699, 'Pizarro');
insert into cities (city_id, city_name) values (700, 'Al Jawādīyah');
insert into cities (city_id, city_name) values (701, 'Sanjiazi');
insert into cities (city_id, city_name) values (702, 'Pajala');
insert into cities (city_id, city_name) values (703, 'Columbus');
insert into cities (city_id, city_name) values (704, 'Santa Cecília');
insert into cities (city_id, city_name) values (705, 'Umi');
insert into cities (city_id, city_name) values (706, 'Biruinţa');
insert into cities (city_id, city_name) values (707, 'San Isidro');
insert into cities (city_id, city_name) values (708, 'Heshi');
insert into cities (city_id, city_name) values (709, 'Tonekābon');
insert into cities (city_id, city_name) values (710, 'Ampelókipoi');
insert into cities (city_id, city_name) values (711, 'Aranhas');
insert into cities (city_id, city_name) values (712, 'Itaqui');
insert into cities (city_id, city_name) values (713, 'Zhenjiang');
insert into cities (city_id, city_name) values (714, 'Amherstburg');
insert into cities (city_id, city_name) values (715, 'Baugo');
insert into cities (city_id, city_name) values (716, 'Novoselë');
insert into cities (city_id, city_name) values (717, 'København');
insert into cities (city_id, city_name) values (718, 'Jokkmokk');
insert into cities (city_id, city_name) values (719, 'Zeist');
insert into cities (city_id, city_name) values (720, 'Qamdo');
insert into cities (city_id, city_name) values (721, 'Victoria');
insert into cities (city_id, city_name) values (722, 'Landázuri');
insert into cities (city_id, city_name) values (723, 'Kushovë');
insert into cities (city_id, city_name) values (724, 'Krikil');
insert into cities (city_id, city_name) values (725, 'Bin Yauri');
insert into cities (city_id, city_name) values (726, 'São Caetano do Sul');
insert into cities (city_id, city_name) values (727, 'Anaco');
insert into cities (city_id, city_name) values (728, 'Yên Lạc');
insert into cities (city_id, city_name) values (729, 'Mshinskaya');
insert into cities (city_id, city_name) values (730, 'Bang Ban');
insert into cities (city_id, city_name) values (731, 'Ilo');
insert into cities (city_id, city_name) values (732, 'Solna');
insert into cities (city_id, city_name) values (733, 'Wolfville');
insert into cities (city_id, city_name) values (734, 'Resapombo');
insert into cities (city_id, city_name) values (735, 'Emiliano Zapata');
insert into cities (city_id, city_name) values (736, 'Dzüünkharaa');
insert into cities (city_id, city_name) values (737, 'Cungkal');
insert into cities (city_id, city_name) values (738, 'Linköping');
insert into cities (city_id, city_name) values (739, 'Nobo');
insert into cities (city_id, city_name) values (740, 'Kure');
insert into cities (city_id, city_name) values (741, 'Nhà Bàng');
insert into cities (city_id, city_name) values (742, 'Siquisique');
insert into cities (city_id, city_name) values (743, 'Bovec');
insert into cities (city_id, city_name) values (744, 'Doushan');
insert into cities (city_id, city_name) values (745, 'Nantes');
insert into cities (city_id, city_name) values (746, 'Ōtsu-shi');
insert into cities (city_id, city_name) values (747, 'Umeå');
insert into cities (city_id, city_name) values (748, 'Cibitung');
insert into cities (city_id, city_name) values (749, 'Velventós');
insert into cities (city_id, city_name) values (750, 'Yujia');
insert into cities (city_id, city_name) values (751, 'Chanika');
insert into cities (city_id, city_name) values (752, 'Dunyāpur');
insert into cities (city_id, city_name) values (753, 'Kauswagan');
insert into cities (city_id, city_name) values (754, 'Karangbenda');
insert into cities (city_id, city_name) values (755, 'Sabi');
insert into cities (city_id, city_name) values (756, 'Kadugede');
insert into cities (city_id, city_name) values (757, 'Vierzon');
insert into cities (city_id, city_name) values (758, 'Veltruby');
insert into cities (city_id, city_name) values (759, 'Stony Plain');
insert into cities (city_id, city_name) values (760, 'Yasenskaya');
insert into cities (city_id, city_name) values (761, 'San Pedro');
insert into cities (city_id, city_name) values (762, 'Cahul');
insert into cities (city_id, city_name) values (763, 'Visby');
insert into cities (city_id, city_name) values (764, 'Jutrosin');
insert into cities (city_id, city_name) values (765, 'Longxing');
insert into cities (city_id, city_name) values (766, 'Munjungan');
insert into cities (city_id, city_name) values (767, 'Hankha');
insert into cities (city_id, city_name) values (768, 'Dugulubgey');
insert into cities (city_id, city_name) values (769, 'Ringinagung');
insert into cities (city_id, city_name) values (770, 'Pasirdalem');
insert into cities (city_id, city_name) values (771, 'Fort Lauderdale');
insert into cities (city_id, city_name) values (772, 'Nikísiani');
insert into cities (city_id, city_name) values (773, 'Umi');
insert into cities (city_id, city_name) values (774, 'Guanshan');
insert into cities (city_id, city_name) values (775, 'Arroyo Naranjo');
insert into cities (city_id, city_name) values (776, 'Berezna');
insert into cities (city_id, city_name) values (777, 'Ziyang Chengguanzhen');
insert into cities (city_id, city_name) values (778, 'Čeladná');
insert into cities (city_id, city_name) values (779, 'Canalete');
insert into cities (city_id, city_name) values (780, 'Meikeng');
insert into cities (city_id, city_name) values (781, 'São Roque');
insert into cities (city_id, city_name) values (782, 'Vatutine');
insert into cities (city_id, city_name) values (783, 'Káto Nevrokópi');
insert into cities (city_id, city_name) values (784, 'Dubai');
insert into cities (city_id, city_name) values (785, 'Akouda');
insert into cities (city_id, city_name) values (786, 'Seixo');
insert into cities (city_id, city_name) values (787, 'Shangzhuang');
insert into cities (city_id, city_name) values (788, 'Lexington');
insert into cities (city_id, city_name) values (789, 'La Unión');
insert into cities (city_id, city_name) values (790, 'Lins');
insert into cities (city_id, city_name) values (791, 'Pak Chong');
insert into cities (city_id, city_name) values (792, 'Peishe');
insert into cities (city_id, city_name) values (793, 'Reckange-sur-Mess');
insert into cities (city_id, city_name) values (794, 'Bergville');
insert into cities (city_id, city_name) values (795, 'Qanliko’l');
insert into cities (city_id, city_name) values (796, 'Tatarka');
insert into cities (city_id, city_name) values (797, 'Asahikawa');
insert into cities (city_id, city_name) values (798, 'Pengfang');
insert into cities (city_id, city_name) values (799, 'Shūkat aş Şūfī');
insert into cities (city_id, city_name) values (800, 'Duobao');
insert into cities (city_id, city_name) values (801, 'Pedrulheira');
insert into cities (city_id, city_name) values (802, 'Nefta');
insert into cities (city_id, city_name) values (803, 'Xixiang');
insert into cities (city_id, city_name) values (804, 'Holoubkov');
insert into cities (city_id, city_name) values (805, 'A-da-Gorda');
insert into cities (city_id, city_name) values (806, 'Tilik');
insert into cities (city_id, city_name) values (807, 'Radojevo');
insert into cities (city_id, city_name) values (808, 'Haolibao');
insert into cities (city_id, city_name) values (809, 'Haokou');
insert into cities (city_id, city_name) values (810, 'Privodino');
insert into cities (city_id, city_name) values (811, 'Evansville');
insert into cities (city_id, city_name) values (812, 'Lukou');
insert into cities (city_id, city_name) values (813, 'Guocun');
insert into cities (city_id, city_name) values (814, 'Minapan');
insert into cities (city_id, city_name) values (815, 'Columbus');
insert into cities (city_id, city_name) values (816, 'Hongshan');
insert into cities (city_id, city_name) values (817, 'Urkarakh');
insert into cities (city_id, city_name) values (818, 'Ashton');
insert into cities (city_id, city_name) values (819, 'Janowiec');
insert into cities (city_id, city_name) values (820, 'Pittsburgh');
insert into cities (city_id, city_name) values (821, 'Banamba');
insert into cities (city_id, city_name) values (822, 'Kačanik');
insert into cities (city_id, city_name) values (823, 'Mapaniqui');
insert into cities (city_id, city_name) values (824, 'Emiliano Zapata');
insert into cities (city_id, city_name) values (825, 'Araguari');
insert into cities (city_id, city_name) values (826, 'Bello');
insert into cities (city_id, city_name) values (827, 'Ernestinovo');
insert into cities (city_id, city_name) values (828, 'Tagnanan');
insert into cities (city_id, city_name) values (829, 'Saýat');
insert into cities (city_id, city_name) values (830, 'Las Vegas');
insert into cities (city_id, city_name) values (831, 'Bunobogu');
insert into cities (city_id, city_name) values (832, 'Maikawada');
insert into cities (city_id, city_name) values (833, 'Mežica');
insert into cities (city_id, city_name) values (834, 'Rehoboth');
insert into cities (city_id, city_name) values (835, 'Langkapcaang Hilir');
insert into cities (city_id, city_name) values (836, 'North Little Rock');
insert into cities (city_id, city_name) values (837, 'Balzar');
insert into cities (city_id, city_name) values (838, 'Ban Dung');
insert into cities (city_id, city_name) values (839, 'Darkovice');
insert into cities (city_id, city_name) values (840, 'Los Angeles');
insert into cities (city_id, city_name) values (841, 'Krajan Timur Mlokorejo');
insert into cities (city_id, city_name) values (842, 'Cicayur');
insert into cities (city_id, city_name) values (843, 'Anjepy');
insert into cities (city_id, city_name) values (844, 'Gastello');
insert into cities (city_id, city_name) values (845, 'Kukuluk');
insert into cities (city_id, city_name) values (846, 'Farap');
insert into cities (city_id, city_name) values (847, 'Lecong');
insert into cities (city_id, city_name) values (848, 'Chambara');
insert into cities (city_id, city_name) values (849, 'Kozlovice');
insert into cities (city_id, city_name) values (850, 'Fengshan');
insert into cities (city_id, city_name) values (851, 'Shypyntsi');
insert into cities (city_id, city_name) values (852, 'Al Quţayfah');
insert into cities (city_id, city_name) values (853, 'Sindangsari');
insert into cities (city_id, city_name) values (854, 'Xinyang');
insert into cities (city_id, city_name) values (855, 'Vondrozo');
insert into cities (city_id, city_name) values (856, 'Changfu');
insert into cities (city_id, city_name) values (857, 'Pisan');
insert into cities (city_id, city_name) values (858, 'Jacksonville');
insert into cities (city_id, city_name) values (859, 'Vale');
insert into cities (city_id, city_name) values (860, 'Al Jahrā’');
insert into cities (city_id, city_name) values (861, 'Sete Cidades');
insert into cities (city_id, city_name) values (862, 'Cerro Colorado');
insert into cities (city_id, city_name) values (863, 'Phalaborwa');
insert into cities (city_id, city_name) values (864, 'Nabari');
insert into cities (city_id, city_name) values (865, 'Simenqian');
insert into cities (city_id, city_name) values (866, 'Kanganpur');
insert into cities (city_id, city_name) values (867, 'Łomazy');
insert into cities (city_id, city_name) values (868, 'Sao Hai');
insert into cities (city_id, city_name) values (869, 'Aparecida de Goiânia');
insert into cities (city_id, city_name) values (870, 'Siem Reap');
insert into cities (city_id, city_name) values (871, 'Yuen Long Kau Hui');
insert into cities (city_id, city_name) values (872, 'Hyères');
insert into cities (city_id, city_name) values (873, 'Jaguaribe');
insert into cities (city_id, city_name) values (874, 'Bobon');
insert into cities (city_id, city_name) values (875, 'Erandique');
insert into cities (city_id, city_name) values (876, 'Avignon');
insert into cities (city_id, city_name) values (877, 'Kosaya Gora');
insert into cities (city_id, city_name) values (878, 'Aco');
insert into cities (city_id, city_name) values (879, 'Oulmes');
insert into cities (city_id, city_name) values (880, 'Richards Bay');
insert into cities (city_id, city_name) values (881, 'Sakule');
insert into cities (city_id, city_name) values (882, 'Gaya');
insert into cities (city_id, city_name) values (883, 'Pakxong');
insert into cities (city_id, city_name) values (884, 'Bruzual');
insert into cities (city_id, city_name) values (885, 'Simabur');
insert into cities (city_id, city_name) values (886, 'Bugis');
insert into cities (city_id, city_name) values (887, 'Bajing');
insert into cities (city_id, city_name) values (888, 'Bandarbeyla');
insert into cities (city_id, city_name) values (889, 'La Fortuna');
insert into cities (city_id, city_name) values (890, 'Suponevo');
insert into cities (city_id, city_name) values (891, 'Frederico Westphalen');
insert into cities (city_id, city_name) values (892, 'Madalena do Mar');
insert into cities (city_id, city_name) values (893, 'Beigang');
insert into cities (city_id, city_name) values (894, 'Currais');
insert into cities (city_id, city_name) values (895, 'Zagreb - Centar');
insert into cities (city_id, city_name) values (896, 'Doljevac');
insert into cities (city_id, city_name) values (897, 'Adassil');
insert into cities (city_id, city_name) values (898, 'Barotac Nuevo');
insert into cities (city_id, city_name) values (899, 'Yanji');
insert into cities (city_id, city_name) values (900, 'New Bedford');
insert into cities (city_id, city_name) values (901, 'Aydūn');
insert into cities (city_id, city_name) values (902, 'Paris 19');
insert into cities (city_id, city_name) values (903, 'Jingmao');
insert into cities (city_id, city_name) values (904, 'Rehoboth');
insert into cities (city_id, city_name) values (905, 'Zhaxirabdain');
insert into cities (city_id, city_name) values (906, 'Diofior');
insert into cities (city_id, city_name) values (907, 'Tamahú');
insert into cities (city_id, city_name) values (908, 'Himaya');
insert into cities (city_id, city_name) values (909, 'Shangjiangxu');
insert into cities (city_id, city_name) values (910, 'Baiyushan');
insert into cities (city_id, city_name) values (911, 'Rothesay Bay');
insert into cities (city_id, city_name) values (912, 'Donduşeni');
insert into cities (city_id, city_name) values (913, 'Schiedam postbusnummers');
insert into cities (city_id, city_name) values (914, 'Zhangjiaji');
insert into cities (city_id, city_name) values (915, 'Lama');
insert into cities (city_id, city_name) values (916, 'Kuching');
insert into cities (city_id, city_name) values (917, 'Pérez');
insert into cities (city_id, city_name) values (918, 'Curahnongko');
insert into cities (city_id, city_name) values (919, 'Wuxihe');
insert into cities (city_id, city_name) values (920, 'Shuanghe');
insert into cities (city_id, city_name) values (921, 'Pedreira');
insert into cities (city_id, city_name) values (922, 'Jiangchuan');
insert into cities (city_id, city_name) values (923, 'La Reforma');
insert into cities (city_id, city_name) values (924, 'Gelin');
insert into cities (city_id, city_name) values (925, 'Wushishi');
insert into cities (city_id, city_name) values (926, 'Banjar Dharmasemedi');
insert into cities (city_id, city_name) values (927, 'Sepekov');
insert into cities (city_id, city_name) values (928, 'Krajan Gajahmati');
insert into cities (city_id, city_name) values (929, 'München');
insert into cities (city_id, city_name) values (930, 'Dianbu');
insert into cities (city_id, city_name) values (931, 'Sigavé');
insert into cities (city_id, city_name) values (932, 'Shihui');
insert into cities (city_id, city_name) values (933, 'Synya');
insert into cities (city_id, city_name) values (934, 'Nishishinminato');
insert into cities (city_id, city_name) values (935, 'El Doncello');
insert into cities (city_id, city_name) values (936, 'Falköping');
insert into cities (city_id, city_name) values (937, 'Simpang');
insert into cities (city_id, city_name) values (938, 'Aḑ Ḑil‘');
insert into cities (city_id, city_name) values (939, 'Termas de Río Hondo');
insert into cities (city_id, city_name) values (940, 'Juradó');
insert into cities (city_id, city_name) values (941, 'Natitingou');
insert into cities (city_id, city_name) values (942, 'Malata');
insert into cities (city_id, city_name) values (943, 'Besuk Selatan');
insert into cities (city_id, city_name) values (944, 'Lian');
insert into cities (city_id, city_name) values (945, 'Fajsławice');
insert into cities (city_id, city_name) values (946, 'Orléans');
insert into cities (city_id, city_name) values (947, 'Paraćin');
insert into cities (city_id, city_name) values (948, 'Luoluopu');
insert into cities (city_id, city_name) values (949, 'Carrefour');
insert into cities (city_id, city_name) values (950, 'Kawerau');
insert into cities (city_id, city_name) values (951, 'Visaginas');
insert into cities (city_id, city_name) values (952, 'Aoqiao');
insert into cities (city_id, city_name) values (953, 'Koumra');
insert into cities (city_id, city_name) values (954, 'Duofudu');
insert into cities (city_id, city_name) values (955, 'Pahing Jalatrang');
insert into cities (city_id, city_name) values (956, 'Kikinda');
insert into cities (city_id, city_name) values (957, 'Oujda');
insert into cities (city_id, city_name) values (958, 'Tanalt');
insert into cities (city_id, city_name) values (959, 'Korydallós');
insert into cities (city_id, city_name) values (960, 'Al Qābil');
insert into cities (city_id, city_name) values (961, 'Sumalig');
insert into cities (city_id, city_name) values (962, 'Huanggang');
insert into cities (city_id, city_name) values (963, 'Lela');
insert into cities (city_id, city_name) values (964, 'Astghadzor');
insert into cities (city_id, city_name) values (965, 'Mońki');
insert into cities (city_id, city_name) values (966, 'Chadong');
insert into cities (city_id, city_name) values (967, 'Tonggu');
insert into cities (city_id, city_name) values (968, 'Paprotnia');
insert into cities (city_id, city_name) values (969, 'Strachówka');
insert into cities (city_id, city_name) values (970, 'Cimişlia');
insert into cities (city_id, city_name) values (971, 'Zaytā');
insert into cities (city_id, city_name) values (972, 'Monte Branco');
insert into cities (city_id, city_name) values (973, 'Tharyarwady');
insert into cities (city_id, city_name) values (974, 'Utrecht (stad)');
insert into cities (city_id, city_name) values (975, 'Lalagsan');
insert into cities (city_id, city_name) values (976, 'Varser');
insert into cities (city_id, city_name) values (977, 'Ashmūn');
insert into cities (city_id, city_name) values (978, 'Koton Karifi');
insert into cities (city_id, city_name) values (979, 'Nangabere');
insert into cities (city_id, city_name) values (980, 'Upper San Mateo');
insert into cities (city_id, city_name) values (981, 'Aūa');
insert into cities (city_id, city_name) values (982, 'Pingxiang');
insert into cities (city_id, city_name) values (983, 'Tsovazard');
insert into cities (city_id, city_name) values (984, 'Graikochóri');
insert into cities (city_id, city_name) values (985, 'La Rochelle');
insert into cities (city_id, city_name) values (986, 'Lyuban’');
insert into cities (city_id, city_name) values (987, 'Hwasun');
insert into cities (city_id, city_name) values (988, 'Svay Rieng');
insert into cities (city_id, city_name) values (989, 'Hepu');
insert into cities (city_id, city_name) values (990, 'Kirawsk');
insert into cities (city_id, city_name) values (991, 'Tenjolaya');
insert into cities (city_id, city_name) values (992, 'Colombo');
insert into cities (city_id, city_name) values (993, 'Jiuzhen');
insert into cities (city_id, city_name) values (994, 'Gwio Kura');
insert into cities (city_id, city_name) values (995, 'Hoima');
insert into cities (city_id, city_name) values (996, 'Daxing');
insert into cities (city_id, city_name) values (997, 'Armenia');
insert into cities (city_id, city_name) values (998, 'Shangma');
insert into cities (city_id, city_name) values (999, 'Sydney');
insert into cities (city_id, city_name) values (1000, 'Almaznyy');
